name: Auto Merge on Dev Branch Update

on:
  push:
    branches:
      - dev

jobs:
  merge_to_main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Find path 
        uses: pwd

      - name: Run Shell Script
        run: bash hello.sh

      - name: Merge to Main
        run: |
          git checkout main
          git merge dev --no-ff --no-edit
          git push origin main

