name: Run Hello Script

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Hello Script
        run: echo "hello world"
          

steps:
  - name: Merge main to release/.+
    uses: alagos/regex-merge@v1.2
    with:
      accessToken: ${{ secrets.GITHUB_TOKEN }}
      headBranch: main
      branchRegex: '^(release|staging)\/.+'
