name: Run Hello Script

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Hello Script
        run: echo "hello world"
          


      - name: Merge to main branch
        uses: actions/github-script@v4
  with:
    github-token: ${{ secrets.GITHUB_TOKEN }}
    script: |
      const owner = 'kryan1234';
      const repo = 'maomao';
      const head = 'dev';
      const base = 'main';
      const maintainer_can_modify = true;
      
      const github = context.repo;
      const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
      octokit.pulls.create({
        owner: owner,
        repo: repo,
        title: 'Merge dev to main',
        head: head,
        base: base,
        maintainer_can_modify: maintainer_can_modify
      });
