name: Run Hello Script

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Hello Script
        run: |
          chmod +x hello.sh
          ./hello.sh

      - name: Merge to main branch
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const github = context.repo;
            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
            octokit.pulls.create({
              owner: github.owner,
              repo: github.repo,
              title: 'Merge dev to main',
              head: 'dev',
              base: 'main',
              maintainer_can_modify: true
            });
